import { NavBar } from "@/components";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-[100vw] h-[100vh]">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
